amp_dtype: float16
batch_size: 64
checkpoint:
  keep_last: 5
  mode: min
  monitor: val_loss
  save_best: true
  save_dir: ./checkpoints
  save_every: 1000
dataset_path: example_dataset
distributed:
  backend: nccl
  enabled: false
  find_unused_parameters: false
  gradient_as_bucket_view: true
epochs: 20
eval_batch_size: 64
eval_every: 1000
eval_steps: null
gradient_accumulation_steps: 1
logging:
  log_dir: ./logs
  log_every: 100
  use_tensorboard: true
  use_wandb: true
  wandb_entity: null
  wandb_project: example_project
max_grad_norm: 1.0
max_length: 512
max_steps: null
model_name: example_model
num_workers: 4
optimizer:
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  name: adamw
  params: {}
  weight_decay: 0.05
pin_memory: true
resume_from: null
scheduler:
  min_lr: 1.0e-06
  name: cosine
  params: {}
  total_steps: 10000
  warmup_steps: 500
seed: 42
use_amp: true
